## Hyperparameter tuning
- The parameter or arguments of model can change by user to get the good model performance
- Grid search
- Random search
- Assume that in decision tree we have following hyper parameters
    - criterion : {'gini','entropy','log_loss'}
    - splitter : {'best','random'}
    - max_depth : {1,2,3,4,5,6}
- by default we have criterion 'gini' is there
- but the model might be performed well when criterion is entropy
- we need to teste the combinations by providing diff values
- to try the combinations we have two methods:
    - Grid search
      - it is a step by step process considering all the combinations
      - in criterion : 3,splitter : 2, max_depth : 6
      - total combinations : 3*2*6=36
    - Random search
      - it will not do all the 36 possible combintions
      - it will select randomly some combinations
- **Generally we do grid search**
- by doing this we have a term called **cross validation**
### Cross Validation
- cross validationn : cv
- out of these 4 parts every time 3 parts consider as train data , 1 part consider as test data
- P1,P2,P3,P4 are 4 parts of data
- combination 1 : P1+P2+P3 are train data and P4 as test data
    - for combination 1 : we will try to improve model performance by hyperparameter tuning
    - assume there are 36 combination are available in DT
    - for the combination 1 we will do all 36
    - so we have 36 hyperparameter combinations for each combination we have one accuracy
    - so we have total 36 accuracy values
- combination 2 : P1+P2+P4 are train data and P3 as test data
    - for combination 1 : we will try to improve model performance by hyperparameter tuning
    - assume there are 36 combination are available in DT
    - for the combination 1 we will do all 36
    - so we have 36 hyperparameter combinations for each combination we have one accuracy
    - so we have total 36 accuracy values
- combination 3 : P1+P3+P4 are train data and P2 as test data
    - for combination 1 : we will try to improve model performance by hyperparameter tuning
    - assume there are 36 combination are available in DT
    - for the combination 1 we will do all 36
    - so we have 36 hyperparameter combinations for each combination we have one accuracy
    - so we have total 36 accuracy values
- combination 4 : P2+P3+P4 are train data and P1 as test data
    - for combination 1 : we will try to improve model performance by hyperparameter tuning
    - assume there are 36 combination are available in DT
    - for the combination 1 we will do all 36
    - so we have 36 hyperparameter combinations for each combination we have one accuracy
    - so we have total 36 accuracy values
- Every combinationgives accuraccy values corercsponding ecah hyper paramter
- will calculate all the avg accuracy of combinations individual accuracy w.r.t each hyperparameter
- so that we get 36 avg accuracy values w.r.t each hyper parameter
- out of these 36 the max one is our best accuracy and corresponding hyperparameters are best parameters

In [2]:
import pandas as pd
import numpy as np
import sklearn 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
path=r"E:\Downloads\preprocessd_data_cleaned - preprocessd_data_cleaned.csv"

In [4]:
df=pd.read_csv(path)
df

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473,0
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522,0
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507,1
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517,0
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473,0
...,...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473,1
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227,1
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512,1
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468,1
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468,1

In [5]:
X=df.drop('churn',axis=1)
y=df['churn']

In [6]:
X

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473
...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468

In [7]:
y

0       0
1       0
2       1
3       0
4       0
       ..
3401    1
3402    1
3403    1
3404    1
3405    1
Name: churn, Length: 3406, dtype: int64

In [8]:
df.shape

(3406, 11)

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
indexes = [f"h_{i}" for i in range(1,37)]
col1=[f"combination_1_acc_{i}" for i in range(1,37)]
col2=[f"combination_2_acc_{i}" for i in range(1,37)]
col3=[f"combination_3_acc_{i}" for i in range(1,37)]
col4=[f"combination_4_acc_{i}" for i in range(1,37)]
col5=[f"avg_acc_{i}" for i in range(1,37)]
cols=['c1','c2','c3','c4','Avg acc']
pd.DataFrame(zip(col1,col2,col3,col4,col5),index=indexes,columns=cols)

,c1,c2,c3,c4,Avg acc
h_1,combination_1_acc_1,combination_2_acc_1,combination_3_acc_1,combination_4_acc_1,avg_acc_1
h_2,combination_1_acc_2,combination_2_acc_2,combination_3_acc_2,combination_4_acc_2,avg_acc_2
h_3,combination_1_acc_3,combination_2_acc_3,combination_3_acc_3,combination_4_acc_3,avg_acc_3
h_4,combination_1_acc_4,combination_2_acc_4,combination_3_acc_4,combination_4_acc_4,avg_acc_4
h_5,combination_1_acc_5,combination_2_acc_5,combination_3_acc_5,combination_4_acc_5,avg_acc_5
h_6,combination_1_acc_6,combination_2_acc_6,combination_3_acc_6,combination_4_acc_6,avg_acc_6
h_7,combination_1_acc_7,combination_2_acc_7,combination_3_acc_7,combination_4_acc_7,avg_acc_7
h_8,combination_1_acc_8,combination_2_acc_8,combination_3_acc_8,combination_4_acc_8,avg_acc_8
h_9,combination_1_acc_9,combination_2_acc_9,combination_3_acc_9,combination_4_acc_9,avg_acc_9
h_10,combination_1_acc_10,combination_2_acc_10,combination_3_acc_10,combination_4_acc_10,avg_acc_10
h_11,combination_1_acc_11,combination_2_acc_11,combination_3_acc_11,combination_4_acc_11,avg_acc_11
h_12,combination_1_acc_12,combination_2_acc_12,combination_3_acc_12,combination_4_acc_12,avg_acc_12
h_13,combination_1_acc_13,combination_2_acc_13,combination_3_acc_13,combination_4_acc_13,avg_acc_13
h_14,combination_1_acc_14,combination_2_acc_14,combination_3_acc_14,combination_4_acc_14,avg_acc_14
h_15,combination_1_acc_15,combination_2_acc_15,combination_3_acc_15,combination_4_acc_15,avg_acc_15
h_16,combination_1_acc_16,combination_2_acc_16,combination_3_acc_16,combination_4_acc_16,avg_acc_16
h_17,combination_1_acc_17,combination_2_acc_17,combination_3_acc_17,combination_4_acc_17,avg_acc_17
h_18,combination_1_acc_18,combination_2_acc_18,combination_3_acc_18,combination_4_acc_18,avg_acc_18
h_19,combination_1_acc_19,combination_2_acc_19,combination_3_acc_19,combination_4_acc_19,avg_acc_19
h_20,combination_1_acc_20,combination_2_acc_20,combination_3_acc_20,combination_4_acc_20,avg_acc_20
h_21,combination_1_acc_21,combination_2_acc_21,combination_3_acc_21,combination_4_acc_21,avg_acc_21
h_22,combination_1_acc_22,combination_2_acc_22,combination_3_acc_22,combination_4_acc_22,avg_acc_22
h_23,combination_1_acc_23,combination_2_acc_23,combination_3_acc_23,combination_4_acc_23,avg_acc_23
h_24,combination_1_acc_24,combination_2_acc_24,combination_3_acc_24,combination_4_acc_24,avg_acc_24
h_25,combination_1_acc_25,combination_2_acc_25,combination_3_acc_25,combination_4_acc_25,avg_acc_25
h_26,combination_1_acc_26,combination_2_acc_26,combination_3_acc_26,combination_4_acc_26,avg_acc_26
h_27,combination_1_acc_27,combination_2_acc_27,combination_3_acc_27,combination_4_acc_27,avg_acc_27
h_28,combination_1_acc_28,combination_2_acc_28,combination_3_acc_28,combination_4_acc_28,avg_acc_28
h_29,combination_1_acc_29,combination_2_acc_29,combination_3_acc_29,combination_4_acc_29,avg_acc_29
h_30,combination_1_acc_30,combination_2_acc_30,combination_3_acc_30,combination_4_acc_30,avg_acc_30
h_31,combination_1_acc_31,combination_2_acc_31,combination_3_acc_31,combination_4_acc_31,avg_acc_31
h_32,combination_1_acc_32,combination_2_acc_32,combination_3_acc_32,combination_4_acc_32,avg_acc_32
h_33,combination_1_acc_33,combination_2_acc_33,combination_3_acc_33,combination_4_acc_33,avg_acc_33
h_34,combination_1_acc_34,combination_2_acc_34,combination_3_acc_34,combination_4_acc_34,avg_acc_34
h_35,combination_1_acc_35,combination_2_acc_35,combination_3_acc_35,combination_4_acc_35,avg_acc_35
h_36,combination_1_acc_36,combination_2_acc_36,combination_3_acc_36,combination_4_acc_36,avg_acc_36

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [21]:
base_model=DecisionTreeClassifier()
base_model

DecisionTreeClassifier()

In [22]:
base_model.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [83]:
param_grid={
    'criterion': ['gini','entropy'],
    'max_depth': [3,4,5,6,7,8],
    'min_samples_split': [2,3,4],
    'min_samples_leaf': [1,2,3,4],
    'random_state': [0,42]
}

In [85]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV,cross_val_score

In [87]:
grid_search=GridSearchCV(estimator=base_model,param_grid=param_grid,scoring='accuracy',cv=5,verbose=True)
grid_search

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7, 8],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 3, 4],
                         'random_state': [0, 42]},
             scoring='accuracy', verbose=True)

In [89]:
import time 
start=time.time()
grid_search.fit(X_train,y_train)
end=time.time()
print(f'total time taken is {end-start}')

Fitting 5 folds for each of 288 candidates, totalling 1440 fits
total time taken is 30.82979989051819

In [90]:
best_model=grid_search.best_estimator_
best_model

DecisionTreeClassifier(criterion='entropy', max_depth=8, random_state=0)

In [91]:
best_score=grid_search.best_score_
best_score

0.8733492984349704

In [92]:
grid_search.best_index_

264

In [93]:
grid_search.cv_results_.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_criterion', 'param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'param_random_state', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [94]:
params=grid_search.cv_results_['params']
len(params)

288

In [95]:
c1_accuracy=grid_search.cv_results_['split0_test_score']
c2_accuracy=grid_search.cv_results_['split1_test_score']
c3_accuracy=grid_search.cv_results_['split2_test_score']
c4_accuracy=grid_search.cv_results_['split3_test_score']
c5_accuracy=grid_search.cv_results_['split4_test_score']

In [96]:
grid_search.best_index_

264

In [97]:
(c1_accuracy[122] + c2_accuracy[122] + c3_accuracy[122] + c4_accuracy[122] + c5_accuracy[122])/5

0.8711440906637886

In [98]:
(c1_accuracy[122] , c2_accuracy[122] , c3_accuracy[122] , c4_accuracy[122] , c5_accuracy[122])

(0.8605504587155963,
 0.8623853211009175,
 0.8623853211009175,
 0.9027522935779817,
 0.8676470588235294)

In [99]:
# develop a evaluation metrics on test data by using best estimator 
# accuracy, pr, re, auc on test data
# the metrics which we developed on same data(test)
# by using with best hyperparameters

In [100]:
best_model.predict(X_test)

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [117]:
import pandas as pd

results = pd.DataFrame(grid_search.cv_results_)

accuracy_df = pd.DataFrame({
    "c1": results["split0_test_score"],
    "c2": results["split1_test_score"],
    "c3": results["split2_test_score"],
    "c4": results["split3_test_score"],
    "c5": results["split4_test_score"]
})

accuracy_df["Avg acc"] = accuracy_df.mean(axis=1)

accuracy_df.index = [f"h_{i}" for i in range(1, len(accuracy_df)+1)]

(accuracy_df)

             c1        c2        c3        c4        c5   Avg acc
h_1    0.831193  0.809174  0.811009  0.823853  0.834559  0.821958
h_2    0.831193  0.809174  0.811009  0.823853  0.834559  0.821958
h_3    0.831193  0.809174  0.811009  0.823853  0.834559  0.821958
h_4    0.831193  0.809174  0.811009  0.823853  0.834559  0.821958
h_5    0.831193  0.809174  0.811009  0.823853  0.834559  0.821958
...         ...       ...       ...       ...       ...       ...
h_284  0.867890  0.864220  0.871560  0.869725  0.871324  0.868944
h_285  0.867890  0.867890  0.873394  0.866055  0.873162  0.869678
h_286  0.867890  0.864220  0.871560  0.869725  0.871324  0.868944
h_287  0.867890  0.867890  0.873394  0.866055  0.873162  0.869678
h_288  0.867890  0.864220  0.871560  0.869725  0.871324  0.868944

[288 rows x 6 columns]

In [121]:
y_pred=best_model.predict(X_test)

In [123]:
y_pred

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [125]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,classification_report
accuracy=accuracy_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
roc_auc=roc_auc_score(y_test,y_pred)
report=classification_report(y_test,y_pred)

In [127]:
print(f'Accuracy : {accuracy}')
print(f'precision : {precision}')
print(f'Recall : {recall}')
print(f'f1 : {f1}')
print(f'roc_auc : {roc_auc}')
print(f'report : {report}')

Accuracy : 0.873900293255132
precision : 0.8947368421052632
Recall : 0.8475073313782991
f1 : 0.8704819277108434
roc_auc : 0.873900293255132
report :               precision    recall  f1-score   support

           0       0.86      0.90      0.88       341
           1       0.89      0.85      0.87       341

    accuracy                           0.87       682
   macro avg       0.87      0.87      0.87       682
weighted avg       0.87      0.87      0.87       682